In [1]:
import numpy as np
import pandas as pd
import yfinance as yf
import datetime as dt
import matplotlib.pyplot as plt
import math


In [2]:
start_date = dt.datetime(2020,4,1)
end_date = dt.datetime(2023,4,1)
 
#loading from yahoo finance
data = yf.download("GOOGL",start_date, end_date)
 
# pd.set_option('display.max_rows', 4)
# pd.set_option('display.max_columns',5)

data.head()

[*********************100%%**********************]  1 of 1 completed


Open       High        Low      Close  Adj Close    Volume
Date                                                                       
2020-04-01  56.200001  56.471001  54.674500  55.105000  55.105000  51970000
2020-04-02  55.000000  56.138500  54.656502  55.851501  55.851501  56410000
2020-04-03  55.735500  55.939499  53.754002  54.634998  54.634998  51374000
2020-04-06  56.650002  59.537498  56.250000  59.159500  59.159500  63320000
2020-04-07  60.850498  61.039001  58.862499  59.127998  59.127998  61620000

In [3]:
# Setting 80 percent data for training
training_data_len = math.ceil(len(data) * .8)
training_data_len 

#Splitting the dataset
# train_data = data[:training_data_len].iloc[:,:1] 
# test_data = data[training_data_len:].iloc[:,:1]
train_data = data[:training_data_len].iloc[:,:] 
test_data = data[training_data_len:].iloc[:,:]
print(train_data.shape, test_data.shape)
train_data.head()

print("Train Max: ", train_data.Open.max())
print("Train Min: ", train_data.Open.min())
print("Test Max: ", test_data.Open.max())
print("Test Min: ", test_data.Open.min())




(605, 6) (151, 6)
Train Max:  151.25
Train Min:  55.0
Test Max:  114.72000122070312
Test Min:  85.4000015258789


In [4]:
# Selecting Open Price values
# dataset_train = train_data.Open.values 
# # Reshaping 1D to 2D array
# dataset_train = np.reshape(dataset_train, (-1,1)) 
# pd.DataFrame(dataset_train).head()
# dataset_train.shape

dataset_train = train_data.values
# Reshaping 2D to 3D array
# dataset_train = np.reshape(dataset_train, (-1,6)) 
# dataset_train = dataset_train[:, :, np.newaxis]
# dataset_train = dataset_train.reshape((605, 6, 1))
# pd.DataFrame(dataset_train).head()
dataset_train.shape


(605, 6)

In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
# scaling dataset
dataset_train = scaler.fit_transform(dataset_train)

dataset_train = np.reshape(dataset_train, (-1,6)) 

print(dataset_train.shape)
# dataset_train = dataset_train[:, :, np.newaxis]
scaled_train = dataset_train.reshape((dataset_train.shape[0], 6, 1))

print(scaled_train[:5])

scaled_train.shape

# pd.DataFrame(scaled_train[:, :, 0]).head()

(605, 6)
[[[0.01246754]
  [0.00555924]
  [0.00967468]
  [0.00493681]
  [0.00493681]
  [0.37456097]]

 [[0.        ]
  [0.00208145]
  [0.00948552]
  [0.01277792]
  [0.01277792]
  [0.41354664]]

 [[0.00764156]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.36932776]]

 [[0.01714287]
  [0.03763323]
  [0.02623363]
  [0.04752453]
  [0.04752453]
  [0.47422029]]

 [[0.0607844 ]
  [0.05333817]
  [0.05369171]
  [0.04719364]
  [0.04719364]
  [0.45929334]]]


(605, 6, 1)

In [72]:
# Selecting Open Price values
# dataset_test = test_data.Open.values  
# Reshaping 1D to 2D array
# dataset_test = np.reshape(dataset_test, (-1,6)) 
# # Normalizing values between 0 and 1
# scaled_test = scaler.fit_transform(dataset_test) 

dataset_test = test_data.values  
# Reshaping 1D to 2D array
scaled_test = scaler.fit_transform(dataset_test) 
scaled_test = np.reshape(dataset_test, (-1,6)) 
scaled_test = scaled_test.reshape((151, 6, 1))
print(*scaled_test[:5])

scaled_test.shape


[[1.14239998e+02]
 [1.16720001e+02]
 [1.14110001e+02]
 [1.16650002e+02]
 [1.16650002e+02]
 [1.69568000e+07]] [[1.14720001e+02]
 [1.15120003e+02]
 [1.10190002e+02]
 [1.10339996e+02]
 [1.10339996e+02]
 [3.72457000e+07]] [[1.09989998e+02]
 [1.10949997e+02]
 [1.08800003e+02]
 [1.09419998e+02]
 [1.09419998e+02]
 [2.11912000e+07]] [[1.10169998e+02]
 [1.10500000e+02]
 [1.07800003e+02]
 [1.08940002e+02]
 [1.08940002e+02]
 [2.75133000e+07]] [[1.10650002e+02]
 [1.10849998e+02]
 [1.08129997e+02]
 [1.08220001e+02]
 [1.08220001e+02]
 [2.86270000e+07]]


(151, 6, 1)

In [65]:
X_train = []
y_train = []
for i in range(50, len(scaled_train)):
	X_train.append(scaled_train[i-50:i, :, 0])
	y_train.append(scaled_train[i, 0])
	# if i <= 51:
	# 	print(X_train)
	# 	print(y_train)
	# 	print()

# pd.DataFrame(X_train).head()

np.array(X_train).shape


(555, 50, 6)

In [74]:
X_test = []
y_test = []
for i in range(50, len(scaled_test)):
	X_test.append(scaled_test[i-50:i, :, 0])
	y_test.append(scaled_test[i, 0])

np.array(X_test).shape

(101, 50, 6)

In [75]:
# The data is converted to Numpy array
X_train, y_train = np.array(X_train), np.array(y_train)

#Reshaping
# X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1],1))
y_train = np.reshape(y_train, (y_train.shape[0],1))
print("X_train :",X_train.shape,"y_train :",y_train.shape)


X_train : (555, 50, 6) y_train : (555, 1)


In [76]:
# The data is converted to numpy array
X_test, y_test = np.array(X_test), np.array(y_test)

#Reshaping
# X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1],1))
y_test = np.reshape(y_test, (y_test.shape[0],1))
print("X_test :",X_test.shape,"y_test :",y_test.shape)


X_test : (101, 50, 6) y_test : (101, 1)
